name: Build wheels

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-24.04
        - windows-2022
        - macos-14

    env:
      CIBW_ARCHS_LINUX: x86_64 i686 aarch64
      CIBW_ARCHS_MACOS: x86_64 universal2
      CIBW_ARCHS_WINDOWS: AMD64 x86 ARM64
      CIBW_BUILD: "cp38-*"
      # Rust does not provide Cargo for musllinux 32-bit, so that needs to be skipped”
      # https://cibuildwheel.pypa.io/en/stable/faq/#building-rust-wheels
      CIBW_SKIP: "*-musllinux_i686"
      # Set up Rust where needed
      # https://cibuildwheel.pypa.io/en/stable/faq/#building-rust-wheels
      CIBW_BEFORE_ALL_LINUX: curl -sSf https://sh.rustup.rs | sh -s -- -y
      CIBW_BEFORE_ALL_MACOS: rustup target add x86_64-apple-darwin
      CIBW_BEFORE_ALL_WINDOWS: rustup target add i686-pc-windows-msvc
      CIBW_ENVIRONMENT_LINUX: "PATH=$HOME/.cargo/bin:$PATH"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.20.0

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: '${{ github.workspace }}/wheelhouse/*.whl'
